
#include "ML51.h"
#include "Init.h"

void Init(void){
	MFP_P16_GPIO;
	MFP_P17_GPIO;
	GPIO_SetMode(Port1,BIT6,GPIO_MODE_INPUT);
	GPIO_SetMode(Port1,BIT7,GPIO_MODE_INPUT);
	GPIO_EnableInt(PIT0,RISING,EDGE,Port1,6);
	GPIO_EnableInt(PIT1,RISING,EDGE,Port1,7);
	GPIO_SetMode(Port2,BIT0|BIT1|BIT2|BIT3|BIT4|BIT5,GPIO_MODE_PUSHPULL);
	GPIO_SetMode(Port0,BIT0|BIT1,GPIO_MODE_PUSHPULL);
	ENABLE_GLOBAL_INTERRUPT; 
}
